# Generated by Django 3.2.20 on 2023-07-26 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateTimeField(blank=True)),
                ('state', models.CharField(choices=[('NEW', 'New'), ('WIP', 'Work in Progress'), ('DEL', 'Delayed'), ('DON', 'Completed')], default='NEW', max_length=3)),
                ('priority', models.CharField(choices=[('LO', 'Low'), ('MI', 'Medium'), ('HI', 'High'), ('CR', 'Critical')], default='LO', max_length=2)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('overdue', models.BooleanField(default=False)),
                ('coowner', models.ManyToManyField(blank=True, related_name='task_coowner', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
